#spring:
#  rsocket:
#    server:
#      port: 7000
socktuator:
  rsocket:
    server:
      enabled: true
  socket:
    server:
      enabled: true
      
#########################################
# The below is not needed for socktuator
# But it is convenient to compare socktuator
# against the actuator web endpoints
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"  
#  endpoint:
#    env:
#      post:
#        enabled: true
#    health:
#      show-details: always